language: node_js

node_js:
  - "14"

before_script:
  - sh prepare-deploy.sh
script:
  - npm run build
deploy:
  provider: pages
  github_token: wihvF9F9Vq/xSV/HqFMu6SbAHG1bvR0zlW/SX9K7j5yvOweh2Np82fJigkgcHT0weiAZvB9+BnIq+aCEABUVVULGfk2lPayc96qzTS4mKwoSH8F4CarxABonSCx5HBhmFQ15T7gdCDbT7HmT91j8PLM41CmeahQ9UrwYWtQNq3ggxHtsTL8LK12i4xnFmSgacV1p26wANQM9DbpACqEOeHQjzR+3Q5T9PuilT4nTEFgsK8oJRhKMMwUpqj45BzX7NdbYeOH/MvOkprOutjTfcpQvEp4RD9mQYUKeCGJggtuNPNCCPy3zzxqaPTXQ+BvnR5QyMtfSx3+Vipci9wCqF5HOSc/twxrDEAS4NZQSQFBHKruix/NFI6vi94ENZbJKZeoeAos7FBnIvaPGJre/64aBAde2+C7/MIkzB11lLqqlkpqgGeAX1CeZ+jClYWQSv1HaKJDPNprtmrHUJgC1V5zL6XNkKjPp9+uO+M1h8ZxE/l4I5A3Ffj0DWUiVjL9PLkrE+3y8YWe0Muckoxz5Ys8adZybAyAkQ+aZ5nJIDLv1BlB4a9RR2P8dKS3IF2/AcVBOtKnTrO976lfEHMJV31DK7jDFd9n/J76ahO6dr60R41Ym0+Td4qqLwRZFPDThQjHiE3vkIcym+K47adNp+rJtd4HvAREzZVW8vUpndjI=
  keep_history: true
  on:
    branch: main